const detallesVentasEnBruto = [
  {
    idOperacion: '1',
    fechaOperacion: '11/11/2025',
    productos: [
      {
        id: '1',
        nombre: 'Agua',
        precio: 100,
        cantidad: 3,
        categoria: 'Bebida',
        tipoPromocion: 'cantidad',
        descripcionPromocion: 'Dto x Cantidad: 15%',
        porcentajeDescuento: 15,
        montoDescuento: 45,
        subtotalSinDescuento: 300,
        subtotalDescuento: 45,
        totalAPagar: 255,
      },
      {
        id: '2',
        nombre: 'Carne',
        precio: 500,
        cantidad: 2,
        categoria: 'Carniceria',
        tipoPromocion: 'categoria',
        descripcionPromocion: 'Dto x Categoria: 10%',
        porcentajeDescuento: 10,
        montoDescuento: 100,
        subtotalSinDescuento: 1000,
        subtotalDescuento: 100,
        totalAPagar: 900,
      },
    ],
    totalSinDescuento: 1300,
    totalDescuento: 145,
    totalConDescuento: 1155,
  },
];

export const ventasRegistradas = [
  {
    idOperacion: '1',
    fechaCompleta: '15/01/2025',
    dia: '15',
    mes: '01',
    anio: '2025',
    productos: [
      {
        id: '1',
        nombre: 'Agua',
        precio: 2000,
        cantidad: 5,
        categoria: 'Bebida',
        tipoPromocion: 'Cantidad',
        descripcionPromocion: 'Dto x Cantidad (15%)',
        porcentajeDescuento: 15,
        montoDescuento: 1500,
        subTotalSinDescuento: 10000,
        subTotalAPagar: 8500,
      },
      {
        id: '3',
        nombre: 'Detergente',
        precio: 2950,
        cantidad: 1,
        categoria: 'Limpieza',
        tipoPromocion: null,
        descripcionPromocion: null,
        porcentajeDescuento: 0,
        montoDescuento: 0,
        subTotalSinDescuento: 2950,
        subTotalAPagar: 2950,
      },
    ],
    subtotalSinDescuento: 12950,
    subtotalDescuento: 1500,
    totalAPagar: 11450,
    pago: 12000,
    vuelto: 550,
  },
  {
    idOperacion: '2',
    fechaCompleta: '10/03/2025',
    dia: '10',
    mes: '08',
    anio: '2025',
    productos: [
      {
        id: '4',
        nombre: 'Asado',
        precio: 13500,
        cantidad: 3,
        categoria: 'Carniceria',
        tipoPromocion: 'Categoria',
        descripcionPromocion: 'Dto x Categoria (10%)',
        porcentajeDescuento: 10,
        montoDescuento: 4050,
        subTotalSinDescuento: 40500,
        subTotalAPagar: 36450,
      },
      {
        id: '2',
        nombre: 'Pan',
        precio: 2800,
        cantidad: 2,
        categoria: 'Panaderia',
        tipoPromocion: null,
        descripcionPromocion: null,
        porcentajeDescuento: 0,
        montoDescuento: 0,
        subTotalSinDescuento: 5600,
        subTotalAPagar: 5600,
      },
    ],
    subtotalSinDescuento: 46100,
    subtotalDescuento: 4050,
    totalAPagar: 42050,
    pago: 43000,
    vuelto: 950,
  },

  {
    idOperacion: '3',
    fechaCompleta: '20/06/2025',
    dia: '20',
    mes: '10',
    anio: '2025',
    productos: [
      {
        id: '5',
        nombre: 'Sprite',
        precio: 3100,
        cantidad: 1,
        categoria: 'Bebida',
        tipoPromocion: null,
        descripcionPromocion: null,
        porcentajeDescuento: 0,
        montoDescuento: 0,
        subTotalSinDescuento: 3100,
        subTotalAPagar: 3100,
      },
      {
        id: '2',
        nombre: 'Pan',
        precio: 2800,
        cantidad: 1,
        categoria: 'Panaderia',
        tipoPromocion: null,
        descripcionPromocion: null,
        porcentajeDescuento: 0,
        montoDescuento: 0,
        subTotalSinDescuento: 2800,
        subTotalAPagar: 2800,
      },
    ],
    subtotalSinDescuento: 5900,
    subtotalDescuento: 0,
    totalAPagar: 5900,
    pago: 6000,
    vuelto: 100,
  },

  {
    idOperacion: '4',
    fechaCompleta: '05/10/2025',
    dia: '05',
    mes: '10',
    anio: '2025',
    productos: [
      {
        id: '3',
        nombre: 'Detergente',
        precio: 2950,
        cantidad: 1,
        categoria: 'Limpieza',
        tipoPromocion: null,
        descripcionPromocion: null,
        porcentajeDescuento: 0,
        montoDescuento: 0,
        subTotalSinDescuento: 2950,
        subTotalAPagar: 2950,
      },
      {
        id: '2',
        nombre: 'Pan',
        precio: 2800,
        cantidad: 2,
        categoria: 'Panaderia',
        tipoPromocion: null,
        descripcionPromocion: null,
        porcentajeDescuento: 0,
        montoDescuento: 0,
        subTotalSinDescuento: 5600,
        subTotalAPagar: 5600,
      },
      {
        id: '5',
        nombre: 'Sprite',
        precio: 3100,
        cantidad: 1,
        categoria: 'Bebida',
        tipoPromocion: null,
        descripcionPromocion: null,
        porcentajeDescuento: 0,
        montoDescuento: 0,
        subTotalSinDescuento: 3100,
        subTotalAPagar: 3100,
      },
    ],
    subtotalSinDescuento: 11650,
    subtotalDescuento: 0,
    totalAPagar: 11650,
    pago: 12000,
    vuelto: 350,
  },
];
