export const mensajes = {
  entradaInvalida: 'Entrada inválida.',
  saludoDespedida: 'Gracias por usar SupermercadoApp',
  saludoBienvenida: 'Bienvenido a Supermecado App',
  ingreseUsuarioContrasena: 'Por favor ingrese su usuario y contraseña para iniciar sesión.',
  idNoExiste: 'El id ingresado no corresponde a un producto del stock',
  nombreProductoConfirmado: 'Nombre del producto confirmado.',
  productoYaExiste: 'El producto ya existe. Debe ingresar un nombre distinto',
  categoriaConfirmada: 'Categoría confirmada',
  opcionSalir: '"Salir" para cerrar la App',
  salirDelMenu: 'Para salir de la app ingrese "salir"',
  opcionVolver: '"Volver" para regresar al menú',
  productoNoEncontrado: 'Producto no encontrado en el stock',
  opcionSalirVolver: ' (Ingrese "Salir" para cerrar la app o "volver" para regresar al menú)',
  categoriasDisponibles: 'Las categorias disponibles son: ',
  ingreseDatosNuevoProducto: 'Ingrese los datos que se solicitan a continuación',
  precioConfirmado: 'Precio confirmado',
  stockConfirmado: 'Stock confirmado',
  inicioSesionInvalida: 'DNI o contraseña incorrectos. Intente nuevamente.',
  rolNoDefinido: 'No tiene un rol definido. Contacte al administrador.',
  productoAgregadoAlStock: 'Producto agregado: ',
  idNoexiste: 'El id ingresado no existe.',
  productoEncontrado: 'Producto encontrado: ',
  productoPorCategoria: 'Actualmente existen esto productos en la categoria seleccionada: ',
  categoriaNoEncontrada: 'La categoria seleccionada no se encuentra en el stock actualmente',
  ventaRegistrada: 'Los productos registrados son los siguientes: ',
};

export const textoPrompts = {
  seleccioneOpcion: 'Seleccione una opción:',
  ingreseIdProducto: 'Ingrese el Id del producto que desea buscar: ',
  ingreseNombreProducto: 'Ingrese el nombre del producto: ', // cambie el nombre, se rompe
  seleccioneCategoria: 'Seleccione la categoria del producto: ',
  ingresePrecio: 'Ingrese el precio del producto (sin el signo $): ',
  ingreseStock: 'Ingrese el stock del producto: ',
  ingreseCantVendida: 'Ingrese la cantidad vendida del producto: ',
  ingresarOtroProducto: '¿Quiere ingresar otro producto? si/no:',
  ingreseDni: 'Ingrese su DNI (sin puntos): ',
  ingreseContrasena: 'Ingrese su contraseña: ',
  confirmePago: '¿Confirma el pago ingresado? si/no: ',
};
